# Generated by Django 5.0.4 on 2024-04-07 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondapp', '0003_client_remove_post_author_remove_product_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
